name = "Cobblemon"
author = "Perry"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d21d47b703415d141bb85b5975b776cd1d1f93ed24ae6c2748dbf21af0483b5b"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
