ENABLE_DEBUG_LOGS = false
REPLACE_GENERATED_SPAWNERS_WITH_COBBLEMON_SPAWNERS = true
REPLACE_SPAWNERS_IN_STRUCTURES_WITH_COBBLEMON_SPAWNERS = true
REPLACE_SPAWNERS_IN_FEATURES = true
REPLACE_ANY_UNSPECIFIED_SPAWNERS_WITH_DEFAULT_COBBLEMON_SPAWNERS = true
ALLOW_SPAWNED_POKEMON_TO_BE_CATCHABLE = false
ALLOW_SPAWNED_POKEMON_TO_BE_DEFEATED_OUTSIDE_OF_BATTLE = false
ALLOW_SPAWNED_POKEMON_TO_BE_AGGRESSIVE = true
REPLACE_MOB_SPAWNERS_BASED_ON_PERCENTAGE = false
MOB_SPAWNER_REPLACEMENT_PERCENTAGE = 0.0
REPLACE_TRIAL_SPAWNERS_BASED_ON_PERCENTAGE = false
TRIAL_SPAWNER_REPLACEMENT_PERCENTAGE = 0.0
