version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 20
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 5.0
paintingCulling = true
leavesCullingMode = "FAST"
leavesCullingAmount = 1
includeMangroveRoots = true
endGatewayCulling = true
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
customportalapi = true
fastitemframes = true
cobblemon_minimons = true
farmersdelight = true
blue_amethyst = true
rad-gyms = true
cobblefurnies = true
rctmod = true
cobblemonraiddens = true
chipped = true
deeperdarker = true
minimons = true
cobblemon_paleontologist = true
cobblemon-additions = true
yungscavebiomes = true
mega_showdown = true
cobblemonpartsrefabricated = true
biomeswevegone = true
movingelevators = true
pokeblocks = true
minecraft = true
visualoverhaul = true
lumymon = true
fireworkcapsules = true
comforts = true
cobblemontrialsedition = true
regions_unexplored = true
cobblecuisine = true
yigd = true
tmcraft = true
cobblemonrepel = true
travelersbackpack = true
sophisticatedstorage = true
fastpaintings = true
cozyhome = true
cobblemontrainerbattle = true
easy_npc = true
beautify = true
waystones = true
handcrafted = true
ftbquests = true
cobblemon = true
moonlight = true
mapkit = true
morevillagers = true
legendarymonuments = true
hybrid-aquatic = true
gravestones = true
